services:

  postgres:
    image: postgres:15
    container_name: postgres-container
    env_file:
      - secrets.env
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: auth_service
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-net

  redis:
    image: redis
    container_name: redis-dev
    ports:
      - "6379:6379"
    networks:
      - spring-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - secrets.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/auth_service
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_REDIS_HOST: redis-dev
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - spring-net

volumes:
  postgres-data:

networks:
  spring-net:
    driver: bridge